# Generated by Django 4.1.7 on 2023-03-26 14:09

import django.core.exceptions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_timeofshift_afternoon_timeofshift_morning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeofshift',
            old_name='afternoon',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='timeofshift',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='timeofshift',
            name='night',
        ),
        migrations.AddField(
            model_name='timeofshift',
            name='time',
            field=models.TimeField(null=True, validators=[django.core.exceptions.ValidationError]),
        ),
    ]
